language: bash

matrix:
  include:
    - os: linux
    - os: osx
      env: HOMEBREW_NO_AUTO_UPDATE=1

before_install:
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then brew install bats; fi

script:
  - make test
