language: bash

matrix:
  include:
    - os: linux
    - os: osx
      env: HOMEBREW_NO_AUTO_UPDATE=1

addons:
  apt:
    packages:
      shunit2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then brew install shunit2; fi

script:
  - make test
