#!/usr/bin/env bash
# ghclone: Cloning GitHub repository via SSH with different URLs
# Copyright (c) 2014-2018 Yu-Jie Lin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Usage: ghclone <url> [name]
# url could be one of:
# GitHub   : https://github.com/{user}/[repo}
#     HTTPS: https://github.com/{user}/{repo}.git
#     SSH  : git@github.com:{user}/{repo}.git
# Gist     : https://gist.github.com/{user}/{repo}
#     HTTPS: https://gist.github.com/{repo}.git
#     SSH  : git@gist.github.com:{repo}.git


ghclone()
{
    local URL user repo
    # +_CP_parse
    URL="${1%.git}"
    URL="${URL%/}"
    repo="${URL##*/}"
    if [[ "$1" == *gist.github.com* ]]; then
        user=''
        repo="${repo##*:}"
        URL="git@gist.github.com:$repo.git"
    else
        URL="${URL%/$repo}"
        user="${URL##*[:/]}"
        URL="git@github.com:$user/$repo.git"
    fi
    # -_CP_parse

    local CMD=(git clone "$URL" )
    [[ ! -z "$2" ]] && CMD+=("$2") && repo="$2"
    "${CMD[@]}" && cd "$repo"
}


# when being sourced, $0 == bash, only invoke main when they are the same
[[ "$0" != "$BASH_SOURCE" ]] || ghclone "$@"
